## Installing Required Packages

To ensure all required packages are available for this notebook, we'll install them from the provided `requirements.txt` file.


# Mathematical Functions Exploration

In this notebook, we'll explore various mathematical functions and their applications. Before diving in, we'll ensure our computational environment is set up correctly.

## Creating a Virtual Environment

If you'd like to keep the dependencies of this project isolated from your main Python environment, it's a good idea to create a virtual environment. We provide an `environments.yml` file which can be used with Conda to create this isolated environment. 

Follow these steps:

1. If you haven't installed Conda, get it from [here](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html).
2. Navigate to the directory containing `environments.yml`.
3. Create the environment by running the following command in your terminal or command prompt:

In [ ]:
!conda env create -f environments.yml

4. Once the environment is created, activate it:

In [ ]:
!conda activate acse_env

## Installing Required Packages

To ensure all required packages are available for this notebook, we'll install them from the provided `requirements.txt` file.

In [ ]:
!pip install -r requirements.txt

Once the installations are complete, we're ready to proceed with the exploration of the mathematical functions.

## Taylor.py

### Function: `exp`


The function `exp` approximates the exponential function \(e^x\) using a Taylor series expansion. This method represents \(e^x\) as an infinite sum of polynomial terms. By truncating the series at `N` terms, we get an approximation. The function can handle both individual numbers and arrays as input.


In [1]:
import numpy as np
from acsefunctions.taylor import exp

# Single value approximation for e^1
result_single = exp(1)
print(f"Approximation for e^1: {result_single}")

# Approximation for e^2 using the first 10 terms of the Taylor series
result_limited_terms = exp(2, N=10)
print(f"Approximation for e^2 with 10 terms: {result_limited_terms}")

# Approximation for an array of values [0, 1]
result_array = exp(np.array([0, 1]))
print(f"Approximations for [0, 1]: {result_array}")

Approximation for e^1: 2.7182818284590455
Approximation for e^2 with 10 terms: 7.388994708994708
Approximations for [0, 1]: [1.         2.71828183]


### Function: `sin`

#### Brief Explanation:

The `sin` function approximates the sine function `sin(x)` using a Taylor series expansion around the point 0. 

Here, the series alternates signs and only uses odd powers of x. The function can take scalar or array-like inputs and will return the approximation for each value. The number of terms used in the approximation can be adjusted with the `N` parameter.

In [1]:
import numpy as np
from acsefunctions.taylor import sin
# Approximation for sin(0)
print(sin(0))

# Approximation for sin values at [0, pi/2, pi]
print(sin(np.array([0, np.pi/2, np.pi])))

0.0
[ 0.00000000e+00  1.00000000e+00 -3.45866918e-16]


Note that the value for sin(pi) is very close to 0. The approximation can be made more accurate by increasing the number of terms:

In [2]:
# The value should give sqrt(3)/2
print("The value should be :", np.sqrt(3)/2,"\n")
print("The first 5 terms gives :", sin(np.pi/3, 5))
print("The first 25 terms gives :", sin(np.pi/3, 25))



The value should be : 0.8660254037844386 

The first 5 terms gives : 0.866025445099781
The first 25 terms gives : 0.8660254037844384


### Function: `Cos`

The `Cos` function approximates the sine function `Cos(x)` using a Taylor series expansion around the point 0. 

Here, the series alternates signs and only uses even powers of x. The function can take scalar or array-like inputs and will return the approximation for each value. The number of terms used in the approximation can be adjusted with the `N` parameter.

In [3]:
import numpy as np
from acsefunctions.taylor import cos

# Approximation for cos(0)
print(cos(0))

# Approximation for cos values at [0, pi/2, pi]
print(cos(np.array([0, np.pi/2, np.pi])))


1.0
[ 1.00000000e+00  4.26446037e-17 -1.00000000e+00]


### Function: `tan`

The `tan` function approximates the tangent function $\tan(x)$ by utilizing the Taylor series expansions of $\sin(x)$ and $\cos(x)$ functions. The formula for tangent in terms of sine and cosine is:

$$ \tan(x) = \frac{\sin(x)}{\cos(x)} $$

Given the Taylor series expansions for both sine and cosine, the function divides the approximation of sine by the approximation of cosine to achieve the tangent value. It is important to be cautious when using this function for values where $\cos(x)$ is close to zero, as this can lead to division by nearly zero and significant inaccuracies.

In [4]:
import numpy as np
from acsefunctions.taylor import tan
# Approximation for tan(0)
print(tan(0))

# Approximation for tan values at [0, pi/4]
print(tan(np.array([0, np.pi/4])))

0.0
[0. 1.]


## Bessel.py

### Function: `factorial`

The `factorial` function computes the factorial of a given integer $n$. The factorial of a non-negative integer $n$, denoted by $n!$, is the product of all positive integers less than or equal to $n$. The factorial function grows very fast and can become very large for relatively small values of $n$. The formula for factorial is:

$$ n! = n \times (n - 1) \times (n - 2) \times \dots \times 2 \times 1 $$

This function is designed to handle both individual numbers as well as arrays of numbers, providing the factorial for each value in the array.



In [6]:
import numpy as np
from acsefunctions.bessel import factorial

# Factorial of 5
print(factorial(5))

# Factorial of values in an array [3, 4, 5]
print(factorial(np.array([3, 4, 5])))


120
[  6  24 120]


### Function: `gamma_function_lanczos`

The `gamma_function_lanczos` computes the gamma function $\Gamma(z)$ using the Lanczos approximation. The gamma function is a generalization of the factorial function to complex numbers, and it's defined for all complex numbers except for non-positive integers. The formula for the gamma function is:

$$ \Gamma(n) = (n - 1)! $$

for positive integers $n$.

The Lanczos approximation provides an efficient and accurate method for calculating the gamma function. The version used here employs the coefficients with $g = 5$. It's crucial to note that the gamma function returns $-\infty$ for negative real values that are whole numbers.

In [7]:
import numpy as np
from acsefunctions.bessel import gamma_function_lanczos

# Gamma function value for 4.5
print(gamma_function_lanczos(4.5))

# Gamma function values for an array [4, 5, 6]
print(gamma_function_lanczos(np.array([4, 5, 6])))

# Gamma function value for a complex number 0.5 + 1j
print(gamma_function_lanczos(0.5 + 1j))

[11.6317284]
[  6.  24. 120.]
[0.30069462-0.42496788j]


### Function: `bessel_function`

The `bessel_function` computes the Bessel function of the first kind, $J_\alpha(x)$, from its series representation. These functions solve Bessel's differential equation and are useful in problems with cylindrical symmetry.

The Bessel function of order $\alpha$ is given by:
$$ J_\alpha(x) = \frac{1}{\pi} \int_0^\pi \cos(\alpha t - x \sin(t)) \, dt $$

For computation, a summation derived from the above integral is used. The `terms` parameter specifies the number of terms in this series. When working with complex numbers, results are in `np.complex128` format; otherwise, they're floats.

In [9]:
import numpy as np
from acsefunctions.bessel import bessel_function
# Bessel function of first kind for order 1 and value 2
print(bessel_function(1, 2))

# Bessel function of first kind for order 0 and value 0.5
print(bessel_function(0, 0.5))

[0.57672481]
[0.93846981]


/Users/tg1523/Library/CloudStorage/OneDrive-Personal/Documents/acse/mpm-assessment-2-acse-tg1523/acsefunctions/bessel.py:149: RuntimeWarning: overflow encountered in multiply
  / (np.complex128(factorial(m)) * gamma_function_lanczos(m + alpha + 1))
